### ISSUE TITLE
Source Code for PDF

### ISSUE THREAD

**Issue by TahomaSoft** [wb2osz/aprsspec#3]
Hi John,

Just saw your issue on my repo from August 8, 2024 and responded.  This is an extension of that issue.

Will you please make your source code for the PDF available? It is hard to collaborate without it, as PDF isn't really editable, and we don't want to propagate the same problem we are both trying to fix; namely, Bob's APRS PDF specs don't have have source code available and we are reconstructing them by hand.

73,

Erik

**Comment by wb2osz** [comment]
Thank you for your interest in improving the APRS Protocol Specification.

The current 1.2 draft C is ready for public consumption.  It already has the corrections, clarifications, and new features in Bob's Addendums 1.1 & 1.2.  It also has some minor fixes and clarifications based on feedback from implementers and other reviewers.  This version will be adopted as the official standard when the original authors are ready to transfer responsibility to the APRS Foundation.  There would be chaos if there were multiple different diverging versions.

If you would like to help, we still need more people to review it and point out any errors, omissions, or anything needing more clarification.

73,
John WB2OSZ
founding member of APRS Foundation

**Comment by TahomaSoft** [comment]
Hi John,

I'm happy to help anyway that is useful.

Regards,

Erik
